#!/usr/bin/env ts-node

const path = require('path');

async function run() {
  const [stepName, ...args] = process.argv.slice(2);
  if (!stepName) {
    console.error(`USAGE run-script <stepName> [...args]`);
    process.exit(1);
  }

  const step = require(path.join(
    __dirname,
    '..',
    'src',
    'steps',
    stepName,
  ))[stepName];
  const result = await step(...args);
  console.log(
    typeof result === 'string'
      ? result
      : JSON.stringify(result, null, 2),
  );
}

async function addAnnotations() {
  let statusCode = 0;
  try {
    await run();
  } catch (e) {
    console.log(e);
    statusCode = 1;
  }
  process.exit(statusCode);
}

addAnnotations();
